### ISSUE TITLE
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraftforge.fml.client.event.ConfigChangedEvent.modID from class *other mod*

### ISSUE THREAD

**Issue by GeneticSteve** [elix-x/Forever-Enough-Items#13]
<spoiler>
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (HardcoreDarkness-MC1.9-1.8.jar)
  PixelCamTilt (pixelcam-mc1.9-1.0.jar)
  ItemPatchingLoader (ItemPhysic Full 1.3 mc1.9.jar)
  FMLPlugin (InventoryTweaks-1.61-dev-43.jar)
  LoadingPlugin (ChunkAnimator-MC1.9-1.1.jar)
  ShoulderPlugin (ShoulderSurfing-1.9-1.0.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 5/15/16 1:52 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.IllegalAccessError: tried to access field net.minecraftforge.fml.client.event.ConfigChangedEvent.modID from class lumien.chunkanimator.ChunkAnimator
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:179)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:772)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:316)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:513)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:346)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.IllegalAccessError: tried to access field net.minecraftforge.fml.client.event.ConfigChangedEvent.modID from class lumien.chunkanimator.ChunkAnimator
    at lumien.chunkanimator.ChunkAnimator.onConfigChanged(ChunkAnimator.java:43)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_14_ChunkAnimator_onConfigChanged_OnConfigChangedEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at code.elix_x.mods.fei.client.jeioverride.JeiReflector.load(JeiReflector.java:157)
    at code.elix_x.mods.fei.api.gui.FEIGuiOverride.loadFromProfile(FEIGuiOverride.java:111)
    at code.elix_x.mods.fei.api.gui.FEIGuiOverride.changeProfile(FEIGuiOverride.java:40)
    at code.elix_x.mods.fei.client.events.FEIGuiOverrideEvents.changeProfile(FEIGuiOverrideEvents.java:18)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_168_FEIGuiOverrideEvents_changeProfile_FEIChangeProfileEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140)
    at code.elix_x.mods.fei.api.profile.Profile.setCurrentProfile(Profile.java:77)
    at code.elix_x.mods.fei.api.profile.Profile.load(Profile.java:156)
    at code.elix_x.mods.fei.proxy.ClientProxy.postInit(ClientProxy.java:105)
    at code.elix_x.mods.fei.ForeverEnoughItemsBase.postInit(ForeverEnoughItemsBase.java:189)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:561)
    at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:228)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:206)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:135)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:770)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.9
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 1563952464 bytes (1491 MB) / 2134114304 bytes (2035 MB) up to 4281597952 bytes (4083 MB)
    JVM Flags: 7 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -Xms2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.23 Powered by Forge 12.16.1.1904 Optifine OptiFine_1.9_HD_U_B1 57 mods loaded, 57 mods active
    Loaded coremods (and transformers): 
LoadingPlugin (HardcoreDarkness-MC1.9-1.8.jar)
  lumien.hardcoredarkness.asm.ClassTransformer
PixelCamTilt (pixelcam-mc1.9-1.0.jar)
  com.replaymod.pixelcam.coremod.CameraTiltCT
ItemPatchingLoader (ItemPhysic Full 1.3 mc1.9.jar)
  com.creativemd.itemphysic.ItemTransformer
FMLPlugin (InventoryTweaks-1.61-dev-43.jar)
  invtweaks.forge.asm.ContainerTransformer
LoadingPlugin (ChunkAnimator-MC1.9-1.1.jar)
  lumien.chunkanimator.asm.ClassTransformer
ShoulderPlugin (ShoulderSurfing-1.9-1.0.jar)
  com.teamderpy.shouldersurfing.asm.ShoulderTransformations
    GL info: ' Vendor: 'Intel' Version: '4.3.0 - Build 10.18.15.4279' Renderer: 'Intel(R) HD Graphics'
    OptiFine Version: OptiFine_1.9_HD_U_B1
    Render Distance Chunks: 8
    Mipmaps: 4
    Anisotropic Filtering: 1
    Antialiasing: 0
    Multitexture: false
    Shaders: KUDA-Shaders v6.2.81 - Lite.zip
    OpenGlVersion: 4.3.0 - Build 10.18.15.4279
    OpenGlRenderer: Intel(R) HD Graphics
    OpenGlVendor: Intel
    CpuCount: 2
</spoiler>

**Comment by Elix-x** [comment]
Caused by chunk animator.
@lumien231 Update to latest forge.
