### ISSUE TITLE
Crash during startup-Single Player-1.8.9 - MooFluids - NCDF RegistryNamespaced

### ISSUE THREAD

**Issue by ghost** [elix-x/Forever-Enough-Items#16]
Console throws out a 'Caught exception from FEI' error during startup that causes a crash.

Minecraft 1.8.9
Forge 11.15.1.1855+
FEI 1.0

[Latest.log](https://pastenib.com/v/Yr9QVQ1L1lP7P1PmvEkx)
[Crash Report](https://pastenib.com/v/1zqXIgRPTJHewLvQe6MJ)

**Comment by Elix-x** [comment]
Mkae sure that you're using latest forge (latest, not recomended).

**Comment by ghost** [comment]
Sorry it took so long for an update. I deleted all mods besides:

ExCore 1.0
FEI 1.0
JEI 2.28.18.186
Forge 11.15.1.1902

and it started up just fine. I was able to create a new world and test it. Must be something with another mod... :cry:

**Comment by ghost** [comment]
#https://github.com/TheRoBrit/Moo-Fluids/issues/35

It's [Moo Fluids](http://minecraft.curseforge.com/projects/moo-fluids?gameCategorySlug=mc-mods&projectID=74254&cookieTest=1) that's causing the crash.

ExCore 1.0
FEI 1.0
JEI 2.28.18.186
Moo Fluids 1.6.03.20a
Forge 11.15.1.1902

[Latest Log](https://pastenib.com/v/6PxyDgUZHLwIrHZw7rGq)
[Crash Report](https://pastenib.com/v/chTOLXud0PrLJs3EcNjN)

**Comment by Elix-x** [comment]
Ok, so that's mod interaction... If i read TheRoBrit/Moo-Fluids#35 correctly.

**Comment by ghost** [comment]
Yes, that's what I'm guessing. I just opened up a ticket on Moo Fluid too just to make sure they know about it.

**Comment by Elix-x** [comment]
I saw that. It may be on both my and his end. So we are waiting for @TheRoBrit to respond.

**Comment by ghost** [comment]
Okay. Thanks for looking into it. I appreciate it.

**Comment by Elix-x** [comment]
You're welcome.

**Comment by RoBrit** [comment]
Hi,

This is most likely a bug within the FEI codebase, I believe it's upon attempting to do reflection to manipulate a function that is declared as static. (As shown from the Forge logs) 

Within the Forge log itself it also shows that FEI is the mod that is erroring in the report and that MooFluids is completing its load cycle fully.

As to what you need to do to resolve this issue from your end I'm not fully sure, however I'd assume it'd be checking the function and finding whether it's mutable by sub-classes (which I assume may be the use-case for the reflection)

**Comment by Elix-x** [comment]
No, i'm not using reflection at this line...
I wanted to say "let's look in code", but when looking through logs, i found excpetion being generated by FEI and moo fluids (look in 2nd log, [this one](https://pastenib.com/v/6PxyDgUZHLwIrHZw7rGq)), more specifically, at this part:

```
[12:59:18] [Client thread/ERROR]: Caught exception from FEI
java.lang.IncompatibleClassChangeError: Expecting non-static method com.robrit.moofluids.common.event.ConfigurationHandler.onConfigurationChanged(Lnet/minecraftforge/fml/client/event/ConfigChangedEvent$OnConfigChangedEvent;)V
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_31_ConfigurationHandler_onConfigurationChanged_OnConfigChangedEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at code.elix_x.mods.fei.client.jeioverride.JeiReflector.load(JeiReflector.java:164) ~[JeiReflector.class:?]
    at code.elix_x.mods.fei.api.gui.FEIGuiOverride.loadFromProfile(FEIGuiOverride.java:111) ~[FEIGuiOverride.class:?]
    at code.elix_x.mods.fei.api.gui.FEIGuiOverride.changeProfile(FEIGuiOverride.java:40) ~[FEIGuiOverride.class:?]
    at code.elix_x.mods.fei.client.events.FEIGuiOverrideEvents.changeProfile(FEIGuiOverrideEvents.java:18) ~[FEIGuiOverrideEvents.class:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_28_FEIGuiOverrideEvents_changeProfile_FEIChangeProfileEvent.invoke(.dynamic) ~[?:?]
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:49) ~[ASMEventHandler.class:?]
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:140) ~[EventBus.class:?]
    at code.elix_x.mods.fei.api.profile.Profile.setCurrentProfile(Profile.java:77) ~[Profile.class:?]
    at code.elix_x.mods.fei.api.profile.Profile.load(Profile.java:156) ~[Profile.class:?]
    at code.elix_x.mods.fei.proxy.ClientProxy.postInit(ClientProxy.java:105) ~[ClientProxy.class:?]
    at code.elix_x.mods.fei.ForeverEnoughItemsBase.postInit(ForeverEnoughItemsBase.java:189) ~[ForeverEnoughItemsBase.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:560) ~[forge-1.8.9-11.15.1.1902-1.8.9-universal.jar:?]
    at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source) ~[?:?]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:211) ~[forge-1.8.9-11.15.1.1902-1.8.9-universal.jar:?]
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:189) ~[forge-1.8.9-11.15.1.1902-1.8.9-universal.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304) ~[guava-17.0.jar:?]
    at com.google.common.eventbus.EventBus.post(EventBus.java:275) ~[guava-17.0.jar:?]
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:118) [LoadController.class:?]
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:742) [Loader.class:?]
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:310) [FMLClientHandler.class:?]
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:495) [ave.class:?]
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:329) [ave.class:?]
    at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_92]
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_92]
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_92]
    at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_92]
    at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:310) [NewLaunch.jar:?]
    at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:395) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.listen(EntryPoint.java:170) [NewLaunch.jar:?]
    at org.multimc.EntryPoint.main(EntryPoint.java:54) [NewLaunch.jar:?]
```

It references both FEI and moo fluids, and especially tells that problem is in moo fluids event handler.

**Comment by ghost** [comment]
Huh, it seems like he just told us to fuck off....

**Comment by Elix-x** [comment]
1.8.9 is no longer supported.

**Comment by Elix-x** [comment]
If you are still experiencing this in 1.10.2, please open a new issue, with relevant crash & logs.
Thank you.
